### ISSUE TITLE
Invitation from OneDegree SRE

### ISSUE THREAD

**Issue by tpai** [chiehting/chiehting.github.io#2]
Hi Chieh Ting,

This is SRE from OneDegree, my name is Tony, we are interesting on your work and would like to invite you to join our interview process, since our HR Nio Kao has contacted you via LinkedIn, you can get back to her or provide me a better way to contact you, looking forward to hearing from you.

JD: https://www.yourator.co/companies/OneDegree/jobs/18670

---
Tony Pai
Senior Engineer

A: 7F., No. 460, Sec. 4, Xinyi Rd., Xinyi Dist., Taipei City 110, Taiwan (R.O.C.)
E: tony.pai@onedegree.hk
OneDegree

**Comment by chiehting** [comment]
Hi Tony, 

Good evening. Thank you for your contact.
I'm  sorry for the late reply.
Congratulations on this position has been accepted.

Keep in touch. 😁
Thanks and Regards
